apiVersion: v1
kind: Service
metadata:
  name: vedio-minimax-h3-api
spec:
  selector:
    app.kubernetes.io/name: vedio-minimax-h3-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: vedio-mcp-server
spec:
  selector:
    app.kubernetes.io/name: vedio-mcp-server
  ports:
    - name: http
      port: 8000
      targetPort: http
