apiVersion: v1
kind: PersistentVolume
metadata:
  name: vedio-minimax-h3-models-shared
  labels:
    app.kubernetes.io/name: vedio-minimax-h3-api
    app.kubernetes.io/component: model-storage
spec:
  capacity:
    storage: 600Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  volumeMode: Filesystem
  hostPath:
    path: /data/volumes/minimax-h3-models-pvc-5a6871db-50a6-4100-8059-2274175b3f72
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 10.241.109.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minimax-h3-models
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: vedio-minimax-h3-models-shared
  resources:
    requests:
      storage: 600Gi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vedio-projects
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: hostpath
